package ihe.iti.xds_b._2007;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.2
 * 2021-11-11T08:33:44.525Z
 * Generated source version: 3.0.2
 * 
 */
@WebServiceClient(name = "DocumentRepository_Service", 
                  wsdlLocation = "file:/var/lib/jenkins/workspace/hie-module-xdsmediator/src/main/resources/wsdl/XDS.b_DocumentRepository.wsdl",
                  targetNamespace = "urn:ihe:iti:xds-b:2007") 
public class DocumentRepositoryService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("urn:ihe:iti:xds-b:2007", "DocumentRepository_Service");
    public final static QName DocumentRepositoryPortSoap12 = new QName("urn:ihe:iti:xds-b:2007", "DocumentRepository_Port_Soap12");
    static {
        URL url = null;
        try {
            url = new URL("file:/var/lib/jenkins/workspace/hie-module-xdsmediator/src/main/resources/wsdl/XDS.b_DocumentRepository.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(DocumentRepositoryService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/var/lib/jenkins/workspace/hie-module-xdsmediator/src/main/resources/wsdl/XDS.b_DocumentRepository.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public DocumentRepositoryService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public DocumentRepositoryService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DocumentRepositoryService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public DocumentRepositoryService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public DocumentRepositoryService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public DocumentRepositoryService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns DocumentRepositoryPortType
     */
    @WebEndpoint(name = "DocumentRepository_Port_Soap12")
    public DocumentRepositoryPortType getDocumentRepositoryPortSoap12() {
        return super.getPort(DocumentRepositoryPortSoap12, DocumentRepositoryPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DocumentRepositoryPortType
     */
    @WebEndpoint(name = "DocumentRepository_Port_Soap12")
    public DocumentRepositoryPortType getDocumentRepositoryPortSoap12(WebServiceFeature... features) {
        return super.getPort(DocumentRepositoryPortSoap12, DocumentRepositoryPortType.class, features);
    }

}
